CREATE DATABASE IF NOT EXISTS PADRON CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci';

CREATE TABLE IF NOT EXISTS PADRON.PROVIN(
	CODPROVINCIA TINYINT,
    NOMBRE_PROVINCIA VARCHAR(25) NOT NULL,
    PRIMARY KEY (CODPROVINCIA)
)ENGINE InnoDB;

CREATE TABLE IF NOT EXISTS PADRON.EMPLEADOS(
	NOMBRE VARCHAR(25),
    EDAD TINYINT,
    COD_PROVIN TINYINT,
    PRIMARY KEY (NOMBRE),
    CONSTRAINT FK_EMPLEADO_PROVINCIA FOREIGN KEY (COD_PROVIN) REFERENCES PROVIN (CODPROVINCIA)
)ENGINE InnoDB;
