CREATE DATABASE IF NOT EXISTS PADRON CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci';

CREATE TABLE IF NOT EXISTS PADRON.PROVIN(
	CODPROVINCIA TINYINT,
    NOMBRE_PROVINCIA VARCHAR(25) NOT NULL,
    PRIMARY KEY (CODPROVINCIA)
)ENGINE InnoDB;

CREATE TABLE IF NOT EXISTS PADRON.EMPLEADOS(
	NOMBRE VARCHAR(25),
    EDAD TINYINT,
    COD_PROVIN TINYINT,
    PRIMARY KEY (NOMBRE),
    -- CONSTRAINT FK_EMPLEADO_PROVINCIA FOREIGN KEY (COD_PROVIN) REFERENCES PROVIN (CODPROVINCIA) ON DELETE CASCADE SET NULL
)ENGINE InnoDB;

CREATE TABLE IF NOT EXISTS PADRON.BLOQUEPISOS(
	CALLE VARCHAR(30),
	NUMERO SMALLINT,
	PISO TINYINT,
	PUERTA CHAR(1),
	CODIGO_PORTAL SMALLINT(5),
	METROS SMALLINT(5),
	COMENTARIOS VARCHAR(60),
	COD_ZONA TINYINT(2),
	DNI VARCHAR(10),
	PRIMARY KEY (CALLE, NUMERO, PISO, PUERTA),
	CONSTRAINT FK_BLOQUEPISOS_ZONAS FOREIGN KEY (COD_ZONA) REFERENCES ZONAS (COD_ZONA),
	CONSTRAINT FK_BLOQUEPISOS_PERSONAS FOREIGN KEY (DNI) REFERENCES PERSONAS (DNI)
)ENGINE InnoDB;

CREATE TABLE IF NOT EXISTS PADRON.ZONAS(
	COD_ZONA TINYINT,
	NOMBREZONA VARCHAR(20),
	MASDATOS VARCHAR(50),
	PRIMARY KEY (COD_ZONA)
)ENGINE InnoDB;

CREATE TABLE IF NOT EXISTS PADRON.PERSONAS(
	DNI VARCHAR(10),
	NOMBRE VARCHAR(30),
	DIRECCION VARCHAR(50),
	POBLACION VARCHAR(40),
	CODPROVIN TINYINT,
	PRIMARY KEY (DNI),
	CONSTRAINT FK_PERSONAS_PROVIN FOREIGN KEY (CODPROVIN) REFERENCES PROVIN (CODPROVINCIA) SET NULL ON DELETE CASCADE
)ENGINE InnoDB;


